### ISSUE TITLE
iis_app resource is not idempotent

### ISSUE THREAD

**Issue by endakenny** [opscode-cookbooks/iis#181] opened 2015-05-19 11:49 UTC
Im linking to the same issue that was logged(and fixed i thought) some time back - link below.

https://github.com/opscode-cookbooks/iis/issues/113

The iis_app physical path is not set in a case where the iis-app already exists but points to another path. 

Ive done a simple test cookbook using iis 4.1.1 from supermarket. 

metadata.rb
---------------
name             'check-iis_app-idempotence'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures check-iis_app-idempotence'
long_description 'Installs/Configures check-iis_app-idempotence'
version          '0.1.1'

depends 		 		 'iis',	'= 4.1.1'

Recipe:
----------
#
# Cookbook Name:: check-iis_app-idempotence
# Recipe:: default
#
# Copyright (c) 2015 The Authors, All Rights Reserved.
iis_app "teste env1 f" do
  path "/hseo5/1"           
  application_pool "teste env1 f"
  physical_path "C:\\Websites\\teste\\env1\\f\\hseo5\\HSEO Framework 5_0_20140829.1\\FrameworkHSEO5\\FrameworkHSEO5"
  enabled_protocols "http,net.tcp"
  action :add
end

**Comment by EasyAsABC123** [comment] 2015-05-19 12:19
you are correct, on the `action :add` it will not update anything if the app already exists...

a temporary workaround is to add `action [:add, :config]` this will resolve your issue...i'll look into other providers and determine the best solution.  However, this is how all of the other providers (in iis) behave as well.

**Comment by endakenny** [comment] 2015-05-19 12:33
Hi Justin

I suspected as much but was unsure.
So just to be clear re the workaround, do I need a need second resource
with the config action or can I have the create and config in the same
resource?

Like this?

application_pool "teste env1 f"
physical_path "C:\Websites\teste\env1\f\hseo5\HSEO Framework
5_0_20140829.1\FrameworkHSEO5\FrameworkHSEO5"
enabled_protocols "http,net.tcp"
action [ :add, :config ]
end

**Comment by EasyAsABC123** [comment] 2015-05-19 12:52
That works perfectly both together

Justin Schuhmann

**Comment by endakenny** [comment] 2015-05-19 13:00
Thanks - that work great - thank you!

**Comment by EasyAsABC123** [comment] 2015-05-19 13:33
Not a problem I'll look into what we can do about edit...but I think since it is only bound to if it exists or not that's just how it works...

Please leave this open while I do some research.

Justin Schuhmann

**Comment by EasyAsABC123** [comment] 2015-05-22 21:19
i'm going to close this under "operating as intended"

**Closed by EasyAsABC123** 2015-05-22 21:19 UTC
